In [43]:
#1. Importar librerías

# Importamos la librería pandas, que se usa para manipulación y análisis de datos
import pandas as pd

In [44]:
#2. Cargar el dataset

# Cargamos el archivo CSV que contiene el dataset de Netflix
df = pd.read_csv("netflix_titles.csv")

# Mostramos las primeras 5 filas del dataset para conocer su estructura
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [45]:
#3. Exploración inicial de los datos

# Ver la cantidad de filas y columnas del dataset
df.shape

# Mostrar los nombres de todas las columnas del dataset
df.columns

# Obtener información general del dataset:
# tipo de datos, cantidad de valores no nulos y memoria utilizada
df.info()

# Mostrar estadísticas descriptivas de las columnas
# include="all" permite analizar también columnas de texto
df.describe(include="all")

<class 'pandas.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   str
 1   type          8807 non-null   str
 2   title         8807 non-null   str
 3   director      6173 non-null   str
 4   cast          7982 non-null   str
 5   country       7976 non-null   str
 6   date_added    8797 non-null   str
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   str
 9   duration      8804 non-null   str
 10  listed_in     8807 non-null   str
 11  description   8807 non-null   str
dtypes: int64(1), str(11)
memory usage: 825.8 KB

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
count,8807,8807,8807,6173,7982,7976,8797,8807.000000,8803,8804,8807,8807
unique,8807,2,8807,4528,7692,748,1767,NaN,17,220,514,8775
top,s1,Movie,Dick Johnson Is Dead,Rajiv Chilaka,David Attenborough,United States,"January 1, 2020",NaN,TV-MA,1 Season,"Dramas, International Movies","Paranormal activity at a lush, abandoned prope..."
freq,1,6131,1,19,19,2818,109,NaN,3207,1793,362,4
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014.180198,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.819312,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1925.000000,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2013.000000,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017.000000,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019.000000,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021.000000,NaN,NaN,NaN,NaN

In [46]:
#4. Identificación de valores nulos

# Identificar cuántos valores nulos existen en cada columna
# Esto es importante para el proceso de limpieza de datos
df.isnull().sum()

show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added        10
release_year       0
rating             4
duration           3
listed_in          0
description        0
dtype: int64

In [47]:
#5. Limpieza de datos

# Reemplazar valores nulos en la columna "director"
# Se reemplazan por la palabra "Desconocido"
df["director"] = df["director"].fillna("Desconocido")

# Reemplazar valores nulos en la columna "country"
df["country"] = df["country"].fillna("No especificado")

# Eliminar filas donde no exista información en la columna date_added, ya que esta variable se utilizará para análisis posteriores
df = df.dropna(subset=["date_added"])

In [48]:
#6. Transformación de datos

# Algunos registros tienen espacios al inicio de la fecha, lo que genera errores al convertir el formato.
# Por eso primero eliminamos los espacios con str.strip()
# errors="coerce" hace que si alguna fecha está mal escrita se convierta en NaN en lugar de generar error.

df["date_added"] = df["date_added"].str.strip()

df["date_added"] = pd.to_datetime(df["date_added"], errors="coerce")

In [49]:
#7. Creación de nuevas variables

# Crear una nueva columna llamada "year_added"
# Esta columna contiene el año en que el contenido fue agregado a Netflix
df["year_added"] = df["date_added"].dt.year

# Visualizar nuevamente el dataset para confirmar la nueva columna creada
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,year_added
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,2021-09-25,2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm...",2021
1,s2,TV Show,Blood & Water,Desconocido,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,2021-09-24,2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",2021
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",No especificado,2021-09-24,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...,2021
3,s4,TV Show,Jailbirds New Orleans,Desconocido,NaN,No especificado,2021-09-24,2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo...",2021
4,s5,TV Show,Kota Factory,Desconocido,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,2021-09-24,2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...,2021

In [50]:
#8. Selección de columnas

# Seleccionar solo algunas columnas del dataset
# Esto permite trabajar únicamente con la información necesaria
df[["title", "type", "country", "release_year"]].head()

                   title     type          country  release_year
0   Dick Johnson Is Dead    Movie    United States          2020
1          Blood & Water  TV Show     South Africa          2021
2              Ganglands  TV Show  No especificado          2021
3  Jailbirds New Orleans  TV Show  No especificado          2021
4           Kota Factory  TV Show            India          2021

In [51]:
#9. Aplicar filtros

#Películas después de 2015

# Filtrar únicamente las películas cuyo año de lanzamiento sea mayor a 2015
movies_2015 = df[(df["type"] == "Movie") & (df["release_year"] > 2015)]

# Mostrar las primeras filas del resultado
movies_2015.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,year_added
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,2021-09-25,2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm...",2021
6,s7,Movie,My Little Pony: A New Generation,"Robert Cullen, José Luis Ucha","Vanessa Hudgens, Kimiko Glenn, James Marsden, ...",No especificado,2021-09-24,2021,PG,91 min,Children & Family Movies,Equestria's divided. But a bright-eyed hero be...,2021
9,s10,Movie,The Starling,Theodore Melfi,"Melissa McCarthy, Chris O'Dowd, Kevin Kline, T...",United States,2021-09-24,2021,PG-13,104 min,"Comedies, Dramas",A woman adjusting to life after a loss contend...,2021
12,s13,Movie,Je Suis Karl,Christian Schwochow,"Luna Wedler, Jannis Niewöhner, Milan Peschel, ...","Germany, Czech Republic",2021-09-23,2021,TV-MA,127 min,"Dramas, International Movies",After most of her family is murdered in a terr...,2021
13,s14,Movie,Confessions of an Invisible Girl,Bruno Garotti,"Klara Castanho, Lucca Picon, Júlia Gomes, Marc...",No especificado,2021-09-22,2021,TV-PG,91 min,"Children & Family Movies, Comedies",When the clever but socially-awkward Tetê join...,2021

In [52]:
#Series producidas en Estados Unidos

# Filtrar únicamente las series de televisión producidas en Estados Unidos
series_usa = df[(df["type"] == "TV Show") & (df["country"] == "United States")]

# Mostrar algunas filas del resultado
series_usa.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,year_added
15,s16,TV Show,Dear White People,Desconocido,"Logan Browning, Brandon P. Bell, DeRon Horton,...",United States,2021-09-22,2021,TV-MA,4 Seasons,"TV Comedies, TV Dramas",Students of color navigate the daily slights a...,2021
40,s41,TV Show,He-Man and the Masters of the Universe,Desconocido,"Yuri Lowenthal, Kimberly Brooks, Antony Del Ri...",United States,2021-09-16,2021,TV-Y7,1 Season,"Kids' TV, TV Sci-Fi & Fantasy",Mighty teen Adam and his heroic squad of misfi...,2021
55,s56,TV Show,Nailed It,Desconocido,"Nicole Byer, Jacques Torres",United States,2021-09-15,2021,TV-PG,6 Seasons,Reality TV,Home bakers with a terrible track record take ...,2021
67,s68,TV Show,Saved by the Bell,Desconocido,"Mark-Paul Gosselaar, Tiffani Thiessen, Mario L...",United States,2021-09-15,1994,TV-PG,9 Seasons,"Kids' TV, TV Comedies","From middle school to college, best friends Za...",2021
82,s83,TV Show,Lucifer,Desconocido,"Tom Ellis, Lauren German, Kevin Alejandro, D.B...",United States,2021-09-10,2021,TV-14,6 Seasons,"Crime TV Shows, TV Comedies, TV Dramas","Bored with being the Lord of Hell, the devil r...",2021

In [53]:
#10. Agrupar datos

#Cantidad de contenidos por tipo

# Agrupar los datos por tipo de contenido (Movie o TV Show), y contar la cantidad total de títulos en cada categoría
df.groupby("type")["title"].count()

type
Movie      6131
TV Show    2666
Name: title, dtype: int64

In [54]:
#Cantidad de contenidos por país

# Agrupar los datos por país y contar cuántos títulos existen por cada uno
# Luego ordenar los resultados de mayor a menor
df.groupby("country")["title"].count().sort_values(ascending=False).head(10)

country
United States      2812
India               972
No especificado     830
United Kingdom      418
Japan               244
South Korea         199
Canada              181
Spain               145
France              124
Mexico              110
Name: title, dtype: int64

In [55]:
#Contenidos agregados por año

# Agrupar los datos según el año en que fueron agregados a Netflix
df.groupby("year_added")["title"].count()

year_added
2008       2
2009       2
2010       1
2011      13
2012       3
2013      11
2014      24
2015      82
2016     429
2017    1188
2018    1649
2019    2016
2020    1879
2021    1498
Name: title, dtype: int64

In [56]:
#11. Crear nuevas variables

# Crear una nueva columna que clasifique el contenido como "Reciente" o "Antiguo"
# Si el año de lanzamiento es mayor o igual a 2015 se considera reciente
df["categoria_estreno"] = df["release_year"].apply(
    lambda x: "Reciente" if x >= 2015 else "Antiguo"
)

# Visualizar el dataset con la nueva variable creada
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,year_added,categoria_estreno
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,2021-09-25,2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm...",2021,Reciente
1,s2,TV Show,Blood & Water,Desconocido,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,2021-09-24,2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",2021,Reciente
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",No especificado,2021-09-24,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...,2021,Reciente
3,s4,TV Show,Jailbirds New Orleans,Desconocido,NaN,No especificado,2021-09-24,2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo...",2021,Reciente
4,s5,TV Show,Kota Factory,Desconocido,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,2021-09-24,2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...,2021,Reciente

In [57]:
#12. Análisis de datos

#Preguntas de análisis

#Pregunta 1

#¿Qué tipo de contenido predomina en Netflix: películas o series?

# Contar cuántos registros existen para cada tipo de contenido
df["type"].value_counts()

type
Movie      6131
TV Show    2666
Name: count, dtype: int64

In [58]:
# Conclusión del análisis para la pregunta 1

print("CONCLUSIÓN 1: El análisis muestra que las películas representan la mayor parte del contenido disponible en Netflix, lo que indica que la plataforma tiene una mayor oferta de películas en comparación con las series de televisión.")

CONCLUSIÓN 1: El análisis muestra que las películas representan la mayor parte del contenido disponible en Netflix, lo que indica que la plataforma tiene una mayor oferta de películas en comparación con las series de televisión.

In [59]:
#Pregunta 2

#¿Qué países producen más contenido para Netflix?

# Identificar los países con mayor cantidad de títulos en la plataforma
df["country"].value_counts().head(10)

country
United States      2812
India               972
No especificado     830
United Kingdom      418
Japan               244
South Korea         199
Canada              181
Spain               145
France              124
Mexico              110
Name: count, dtype: int64

In [60]:
#Conclusión del análisis para la pregunta 2

print("CONCLUSIÓN 2: Estados Unidos lidera la producción de contenido dentro del catálogo de Netflix, seguido por países como India y Reino Unido, lo que refleja la fuerte presencia de la industria audiovisual estadounidense en la plataforma.")

CONCLUSIÓN 2: Estados Unidos lidera la producción de contenido dentro del catálogo de Netflix, seguido por países como India y Reino Unido, lo que refleja la fuerte presencia de la industria audiovisual estadounidense en la plataforma.

In [61]:
#Pregunta 3

#¿En qué años se agregaron más contenidos a Netflix?

# Analizar cuántos contenidos fueron agregados por año
df["year_added"].value_counts().sort_index()

year_added
2008       2
2009       2
2010       1
2011      13
2012       3
2013      11
2014      24
2015      82
2016     429
2017    1188
2018    1649
2019    2016
2020    1879
2021    1498
Name: count, dtype: int64

In [62]:
#Conclusión del análisis para la pregunta 3

print("CONCLUSIÓN 3: A partir de los resultados se observa que desde 2016 la cantidad de contenidos agregados a Netflix aumentó significativamente, lo que coincide con el crecimiento global de la plataforma y su expansión en diferentes países.")

CONCLUSIÓN 3: A partir de los resultados se observa que desde 2016 la cantidad de contenidos agregados a Netflix aumentó significativamente, lo que coincide con el crecimiento global de la plataforma y su expansión en diferentes países.

In [63]:
#13. Guardar el dataset limpio

# Guardar el dataset después de la limpieza y transformación
# index=False evita que se guarde la columna de índices
df.to_csv("netflix_limpio.csv", index=False)